apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-botiga-backend.fullname" . }}
  labels:
    {{- include "helm-botiga-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-botiga-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-botiga-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-botiga-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.probe.liveness.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.probe.readiness.path }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if .Values.deployment.env }}
              {{- toYaml .Values.deployment.env | nindent 12 }}
            {{- end }}
            {{- if .Values.deployment.analytics.firebase }}
            - name: {{ .Values.deployment.analytics.firebase.appVariableName }}
              value: {{ printf "%s/%s.json" .Values.deployment.analytics.firebase.mountPath .Values.deployment.analytics.firebase.secret | quote }} 
            {{- end }}
          volumeMounts:
          {{- if .Values.deployment.analytics.firebase }}
            - name: {{ .Values.deployment.analytics.firebase.secret }}-volume
              mountPath: "/mnt/app/credentials"
          {{- end }}
      volumes:
        {{- if .Values.deployment.analytics.firebase }}
        - name: {{ .Values.deployment.analytics.firebase.secret }}-volume
          secret:
            secretName: {{ .Values.deployment.analytics.firebase.secret }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
