apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-botiga-backend.fullname" . }}
  labels:
    {{- include "helm-botiga-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.deployment.service.type }}
  ports:
    - port: {{ .Values.deployment.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.deployment.service.type "NodePort" }}
      nodePort: {{ .Values.deployment.service.nodePort }}
      {{- end }}
  selector:
    {{- include "helm-botiga-backend.selectorLabels" . | nindent 4 }}
